### PR TITLE
Multipages & split images

### PR DESCRIPTION
**Pull request by martinheidegger**
Currently enex2sb needs to parse the content and it is then parsed again by html2sb-compiler, this *breaking* change turns the result of `parse()` from a page to a list of pages. It also separates the resources of evernote images to links. The references can be replaced between parsing and stringification.

### CODE REVIEW

**Comment by pastak** [comment]
IMO,  separating page is not task for `html2sb-compiler`. It should be `enex2sb`'s task. This library will only parse html and convert to scrapbox style format.

**Comment by martinheidegger** [comment]
I understand where you are coming from. If the html2sb-compiler does this it creates greater dependencies on htmlparser and you have to process the documents twice. Which doesn't help memory consumption or speed. We already have a `{evernote: true}` option which is why I think this PR is the better option.

**Comment by pastak** [comment]
I understand and agree with your point 😄 

OK, `enex2sb` will be only interface to use this lib with `{evernote: true}` option.

Would you solve conflict to merge?

**Comment by martinheidegger** [comment]
Fixed

**Comment by pastak** [comment]
LGTM

**Pull request merged**
